### ISSUE TITLE
Add NUTCase

### ISSUE THREAD

**Issue by ArthurMitchell42** [awesome-foss/awesome-sysadmin#562]
Can I propose the following tool for interfacing NUT UPS devices to metric scrapers such as Prometheus, JSON consumers such as Uptime Kuma and HomePage.
It also provides a GUI to visualise the current status of devices.

```yaml
name: "NUTCase - NUT and APC GUI, metrics and JSON tool for UPS's"
website_url: "https://github.com/ArthurMitchell42/nutcase/wiki"
source_code_url: "https://github.com/ArthurMitchell42/nutcase"
description: "Links network-ups-tools (NUT) and APC daemon UPS devices to metric scrapers such as Prometheus, JSON consumers such as HomePage and supports a GUI to visualise current UPS status."
licenses:
  - AGPL-3.0
platforms:
  - Python
  - Docker
tags:
  - Status / Uptime pages
  - Monitoring
  - Metrics & Metric Collection
depends_3rdparty: false
demo_url: ""
related_software_url: ""
```
